# https://taskfile.dev

version: "3"
# this Taskfile helps to prepare docs for publishing on GithubPages

vars:
  GREETING: |-
    Usage:
    on local machine use 'task p' or 'task prepub' to get docs ready to push 
    to github.io.
    for Jenkins-based CI CD use 'task build', 'task rename-site' and then 
    'task tar' to get a nice single-file artifact
  # tune the vars below for current project each time when you use this taskfile
  SOURCE_DIR: .
  TARGET_SITE_DIR: ~/repos/djfedos.github.io

includes:
  venv:
    taskfile: ./taskfiles/conda-venv.tasks.yaml
    vars:
      VENV_NAME: mkdocs-automated

tasks:
  default:
    desc: _
    cmds:
      - echo "{{.GREETING}}"
      - task -a
    silent: true

  resolve-deps:
    desc: _
    cmds:
      - pip install mkdocs-material

  build:
    desc: build docs from markdown to html + css
    dir: '{{.SOURCE_DIR}}'
    cmds:
      # feel free to edit and add paths if necessary
      - mkdocs build
    sources:
      - ./docs/index.md
    generates:
      - ./site/index.html

  move-site:
    desc: 'for local machine only: move folder to github.io local repo'
    cmds:
      - cp -fr {{.SOURCE_DIR}}/site/* {{.TARGET_SITE_DIR}}
    sources:
      - '{{.SOURCE_DIR}}/site/index.html'
      - '{{.SOURCE_DIR}}/site/sitemap.xml'
      - '{{.SOURCE_DIR}}/site/assets'
      - '{{.SOURCE_DIR}}/site/search'

    generates:
      - '{{.TARGET_SITE_DIR}}/index.html'
      - '{{.TARGET_SITE_DIR}}/sitemap.xml'
      - '{{.TARGET_SITE_DIR}}/site/assets'
      - '{{.TARGET_SITE_DIR}}/site/search'
      
  prepub:
    desc: 'for local machine: prepare docs to be pushed to github.io'
    cmds:
      - task build
      - task move-site

  pub:
    desc: _
    dir: '{{.TARGET_SITE_DIR}}'
    cmds:
      - git add -A
      - git commit -m"Update docs site (by mkdocs-automated)"
      - git push
